### ISSUE TITLE
error message... device switch permanently between connected, closed : null and reconnected

### ISSUE THREAD

**Issue by uli-2016** [bertreb/pimatic-meross#2]
error [pimatic]: An uncaught exception occurred: TypeError: Cannot read property 'removeListener' of undefined
    at MerossPlugin.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-meross/pimatic-meross.coffee:412:19)
    at MerossPlugin.emit (events.js:203:15)
    at MerossCloudDevice.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-meross/pimatic-meross.coffee:43:12)
    at MerossCloudDevice.emit (events.js:203:15)
    at MqttClient.client.on (/home/pi/pimatic-app/node_modules/pimatic-meross/node_modules/meross-cloud/index.js:293:18)
    at MqttClient.emit (events.js:203:15)
    at TLSSocket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-meross/node_modules/meross-cloud/node_modules/mqtt/lib/client.js:360:10)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:64:24)
    at _handle.close (net.js:606:12)
    at TCP.done (_tls_wrap.js:388:7)
 This is most probably a bug in pimatic or in a module, please report it!

But, I can switch on/off the smartplug...

**Comment by bertreb** [comment]
i will check and fix it
